2022-04-25 16:26:19.746 | INFO     | __main__:server:72 - 启动服务：192.168.23.1:55445
2022-04-25 16:26:19.749 | INFO     | __main__:server:75 - 服务注册开始
2022-04-25 16:26:19.757 | INFO     | __main__:server:82 - 服务注册成功
2022-04-25 16:27:50.958 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (4728), thread 'ThreadPoolExecutor-0_6' (18864):
Traceback (most recent call last):

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000027AA25C0798>
    └ <Thread(ThreadPoolExecutor-0_6, started daemon 18864)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000027AA25C0558>
    └ <Thread(ThreadPoolExecutor-0_6, started daemon 18864)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_6, started daemon 18864)>
    │    │        │    └ (<weakref at 0x0000027ABE576048; to 'ThreadPoolExecutor' at 0x0000027ABE3F4108>, <_queue.SimpleQueue object at 0x0000027ABE3E...
    │    │        └ <Thread(ThreadPoolExecutor-0_6, started daemon 18864)>
    │    └ <function _worker at 0x0000027ABE3FC678>
    └ <Thread(ThreadPoolExecutor-0_6, started daemon 18864)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000027ABE3FC798>
    └ <concurrent.futures.thread._WorkItem object at 0x0000027ABE57D4C8>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000027ABE57D4C8>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000027ABE57CA98>, <grpc._server._RPCState object at 0x0000027ABE57D3C8>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000027ABE57D4C8>
             │    └ <function _unary_response_in_pool at 0x0000027ABE42BDC8>
             └ <concurrent.futures.thread._WorkItem object at 0x0000027ABE57D4C8>

  File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 561, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x0000027ABD0FE0B8>
    └ keyWords: "\350\266\212\345\215\227"

> File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x0000027ABE57D608>
                           │        └ keyWords: "\350\266\212\345\215\227"
                           │          
                           └ <bound method GoodsServicer.GoodsList of <goods_srv.handler.goods.GoodsServicer object at 0x0000027ABE4011C8>>

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 90, in GoodsList
    rsp.data.append(self.convert_model_to_message(good))
    │   │           │    │                        └ <Goods: 423>
    │   │           │    └ <function GoodsServicer.convert_model_to_message at 0x0000027ABDB3D3A8>
    │   │           └ <goods_srv.handler.goods.GoodsServicer object at 0x0000027ABE4011C8>
    │   └ <field property 'GoodsListResponse.data'>
    └ total: 8

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 33, in convert_model_to_message
    info_rsp.logo = goods.brand.logo
    │               │     └ <peewee.ForeignKeyAccessor object at 0x0000027ABDFFDC88>
    │               └ <Goods: 423>
    └ id: 423
      categoryId: 136678
      name: "\350\266\212\345\215\227\350\277\233\345\217\243\347\272\242\345\277\203\347\201\253\351\27...

AttributeError: 'GoodsInfoResponse' object has no attribute 'logo'
