2022-05-10 14:07:29.560 | INFO     | __main__:server:72 - 启动服务：192.168.23.1:54397
2022-05-10 14:07:29.565 | INFO     | __main__:server:75 - 服务注册开始
2022-05-10 14:07:31.204 | INFO     | __main__:server:82 - 服务注册成功
2022-05-10 14:34:36.324 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (3164), thread 'ThreadPoolExecutor-0_8' (2128):
Traceback (most recent call last):

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001DE4074FAF8>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 2128)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001DE4074F8B8>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 2128)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_8, started daemon 2128)>
    │    │        │    └ (<weakref at 0x000001DE437197C8; to 'ThreadPoolExecutor' at 0x000001DE43562108>, <_queue.SimpleQueue object at 0x000001DE4357...
    │    │        └ <Thread(ThreadPoolExecutor-0_8, started daemon 2128)>
    │    └ <function _worker at 0x000001DE43581828>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 2128)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001DE43581948>
    └ <concurrent.futures.thread._WorkItem object at 0x000001DE435DC148>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001DE435DC148>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001DE4383F818>, <grpc._server._RPCState object at 0x000001DE43821DC8>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001DE435DC148>
             │    └ <function _unary_response_in_pool at 0x000001DE435B0EE8>
             └ <concurrent.futures.thread._WorkItem object at 0x000001DE435DC148>

  File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 561, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x000001DE40987268>
    └ userId: 1
      address: "\345\216\246\351\227\250\345\270\202"
      mobile: "13169188007"
      name: "hugo"
      post: "\345\260\275\345\277\253\...

> File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001DE435DC088>
                           │        └ userId: 1
                           │          address: "\345\216\246\351\227\250\345\270\202"
                           │          mobile: "13169188007"
                           │          name: "hugo"
                           │          post: "\345\260\275\345\277\253\...
                           └ <bound method OrderServicer.CreateOrder of <order_srv.handler.order.OrderServicer object at 0x000001DE43584548>>

  File "D:\PythonProjects\shop\order_srv\handler\order.py", line 113, in CreateOrder
    goods_srv_host, goods_srv_port = register.get_host_port(f'Service=="{settings.GOODS_SRV_NAME}"')
                                     │        └ <function ConsulRegister.get_host_port at 0x000001DE43339E58>
                                     └ <common.register.consul.ConsulRegister object at 0x000001DE43706788>

  File "D:\PythonProjects\shop\common\register\consul.py", line 54, in get_host_port
    return service_info["Address"], service_info["Port"]
           │                        └ [{'ID': '3eef3bb4-d02b-11ec-b870-5800e3ca956e', 'Service': 'goods-srv', 'Tags': ['shop', 'hugo', 'srv'], 'Meta': {}, 'Port': ...
           └ [{'ID': '3eef3bb4-d02b-11ec-b870-5800e3ca956e', 'Service': 'goods-srv', 'Tags': ['shop', 'hugo', 'srv'], 'Meta': {}, 'Port': ...

TypeError: list indices must be integers or slices, not str
2022-05-10 14:36:45.056 | INFO     | __main__:on_exit:41 - 注销7918b94c-d027-11ec-bfb8-5800e3ca956e服务
2022-05-10 14:36:45.122 | INFO     | __main__:on_exit:43 - 服务注销成功
